- path: /etc/greetd/config.toml
  content: |
    [terminal]
    vt = 1

    [default_session]
    user = "greeter"
    command = "/bin/dms-greeter --command niri"

- path: /etc/dconf/profile/user
  content: |
    user-db:user
    system-db:local

# To allow old controllers to connect
- path: /etc/modprobe.d/disable-ertm.conf
  content: |
    options bluetooth disable_ertm=Y

- path: /usr/lib/sysusers.d/sysusers-custom.conf
  content: |
    u avahi - "Avahi mDNS daemon" /var/run/avahi-daemon
    g avahi - "Avahi mDNS daemon"

    u abrt - "ABRT user" /etc/abrt
    g abrt - "ABRT group"

    u wsdd - "WSDD service user" /var/lib/wsdd
